MERGE (iLogistics:Industry {name: 'Logistics'})
MERGE (iEdTech:Industry {name: 'EdTech'})
MERGE (iAgri:Industry {name: 'AgriTech'})
MERGE (iCyber:Industry {name: 'Cybersecurity'})

MERGE (uNeha:User {id: 'founder-cargoflow', email: 'ceo@cargoflow.in', full_name: 'Neha Kapoor', role: 'startup'})
MERGE (uRohan:User {id: 'founder-edunova', email: 'founder@edunova.io', full_name: 'Rohan Desai', role: 'startup'})
MERGE (uAnanya:User {id: 'founder-farmstack', email: 'hello@farmstack.ag', full_name: 'Ananya Iyer', role: 'startup'})
MERGE (uJames:User {id: 'founder-securenest', email: 'ceo@securenest.io', full_name: 'James Okonkwo', role: 'startup'})
MERGE (uLeila:User {id: 'founder-mediroute', email: 'team@mediroute.health', full_name: 'Dr. Leila Hassan', role: 'startup'})
MERGE (uKabir:User {id: 'founder-paylattice', email: 'founders@paylattice.com', full_name: 'Kabir Singh', role: 'startup'})
MERGE (uAsha:User {id: 'investor-asha', email: 'asha@horizonvc.com', full_name: 'Asha Rao', role: 'investor'})
MERGE (uMarcus:User {id: 'investor-marcus', email: 'marcus@apexcap.io', full_name: 'Marcus Chen', role: 'investor'})
MERGE (uPriyaN:User {id: 'investor-priya', email: 'priya@catalyst.fund', full_name: 'Priya Nair', role: 'investor'})
MERGE (uTom:User {id: 'investor-tom', email: 'tom@deeptech.angels', full_name: 'Tom Alvarez', role: 'investor'})

MERGE (s5:Startup {id: 'startup-cargoflow', name: 'CargoFlow Logistics', stage: 'Seed', email: 'ceo@cargoflow.in'})
MERGE (s6:Startup {id: 'startup-edunova', name: 'EduNova Skills', stage: 'Seed', email: 'founder@edunova.io'})
MERGE (s7:Startup {id: 'startup-farmstack', name: 'FarmStack', stage: 'Seed', email: 'hello@farmstack.ag'})
MERGE (s8:Startup {id: 'startup-securenest', name: 'SecureNest', stage: 'Series A', email: 'ceo@securenest.io'})
MERGE (s9:Startup {id: 'startup-mediroute', name: 'MediRoute', stage: 'Pre-Seed', email: 'team@mediroute.health'})
MERGE (s10:Startup {id: 'startup-paylattice', name: 'PayLattice', stage: 'Seed', email: 'founders@paylattice.com'})

MERGE (uNeha)-[:OWNS]->(s5)
MERGE (uRohan)-[:OWNS]->(s6)
MERGE (uAnanya)-[:OWNS]->(s7)
MERGE (uJames)-[:OWNS]->(s8)
MERGE (uLeila)-[:OWNS]->(s9)
MERGE (uKabir)-[:OWNS]->(s10)

MERGE (s5)-[:OPERATES_IN]->(iLogistics)
MERGE (s6)-[:OPERATES_IN]->(iEdTech)
MERGE (s7)-[:OPERATES_IN]->(iAgri)
MERGE (s8)-[:OPERATES_IN]->(iCyber)
MERGE (s9)-[:OPERATES_IN]->(iHealthTech)
MERGE (s10)-[:OPERATES_IN]->(iFinTech)

MERGE (inv4:Investor {id: 'investor-asha', name: 'Asha Rao', firm: 'Horizon Ventures', email: 'asha@horizonvc.com'})
MERGE (inv5:Investor {id: 'investor-marcus', name: 'Marcus Chen', firm: 'Apex Capital', email: 'marcus@apexcap.io'})
MERGE (inv6:Investor {id: 'investor-priya', name: 'Priya Nair', firm: 'Catalyst Seed Fund', email: 'priya@catalyst.fund'})
MERGE (inv7:Investor {id: 'investor-tom', name: 'Tom Alvarez', firm: 'DeepTech Angels', email: 'tom@deeptech.angels'})

MERGE (uAsha)-[:OWNS]->(inv4)
MERGE (uMarcus)-[:OWNS]->(inv5)
MERGE (uPriyaN)-[:OWNS]->(inv6)
MERGE (uTom)-[:OWNS]->(inv7)

MERGE (d5:Deal {id: 'deal-cargoflow', title: 'AI Lane Pricing for Cold-Chain Freight', status: 'published', industry: 'Logistics', funding_stage: 'Seed', target_raise: 600000})
MERGE (d6:Deal {id: 'deal-edunova', title: 'Outcome-Tied B2B Upskilling Marketplace', status: 'negotiating', industry: 'EdTech', funding_stage: 'Seed', target_raise: 500000})
MERGE (d7:Deal {id: 'deal-farmstack', title: 'FPO Marketplace with Spoilage IoT', status: 'published', industry: 'AgriTech', funding_stage: 'Seed', target_raise: 450000})
MERGE (d8:Deal {id: 'deal-securenest', title: 'Cloud Workload Identity Mesh', status: 'active', industry: 'Cybersecurity', funding_stage: 'Series A', target_raise: 1800000})
MERGE (d9:Deal {id: 'deal-mediroute', title: 'Pharma Last-Mile Cold Routing', status: 'published', industry: 'HealthTech', funding_stage: 'Pre-Seed', target_raise: 300000})
MERGE (d10:Deal {id: 'deal-paylattice', title: 'Embedded Payout Orchestration API', status: 'negotiating', industry: 'FinTech', funding_stage: 'Seed', target_raise: 850000})

MERGE (s5)-[:LISTED]->(d5)
MERGE (s6)-[:LISTED]->(d6)
MERGE (s7)-[:LISTED]->(d7)
MERGE (s8)-[:LISTED]->(d8)
MERGE (s9)-[:LISTED]->(d9)
MERGE (s10)-[:LISTED]->(d10)

MERGE (inv4)-[:INTERESTED_IN {status: 'interested'}]->(d5)
MERGE (inv6)-[:INTERESTED_IN {status: 'active_negotiation'}]->(d6)
MERGE (inv5)-[:INTERESTED_IN {status: 'active_negotiation'}]->(d8)
MERGE (inv7)-[:INTERESTED_IN {status: 'interested'}]->(d8)
MERGE (inv2)-[:INTERESTED_IN {status: 'active_negotiation'}]->(d10)
